export interface Pokemon {
  name: string;
  types: string[];
}

const pokemon: Pokemon[] = [
  { name: 'bulbasaur', types: ['grass', 'poison'] },
  { name: 'ivysaur', types: ['grass', 'poison'] },
  { name: 'venusaur', types: ['grass', 'poison'] },
  { name: 'charmander', types: ['fire'] },
  { name: 'charmeleon', types: ['fire'] },
  { name: 'charizard', types: ['fire', 'flying'] },
  { name: 'squirtle', types: ['water'] },
  { name: 'wartortle', types: ['water'] },
  { name: 'blastoise', types: ['water'] },
  { name: 'caterpie', types: ['bug'] },
  { name: 'metapod', types: ['bug'] },
  { name: 'butterfree', types: ['bug', 'flying'] },
  { name: 'weedle', types: ['bug', 'poison'] },
  { name: 'kakuna', types: ['bug', 'poison'] },
  { name: 'beedrill', types: ['bug', 'poison'] },
  { name: 'pidgey', types: ['normal', 'flying'] },
  { name: 'pidgeotto', types: ['normal', 'flying'] },
  { name: 'pidgeot', types: ['normal', 'flying'] },
  { name: 'rattata', types: ['normal'] },
  { name: 'raticate', types: ['normal'] },
  { name: 'spearow', types: ['normal', 'flying'] },
  { name: 'fearow', types: ['normal', 'flying'] },
  { name: 'ekans', types: ['poison'] },
  { name: 'arbok', types: ['poison'] },
  { name: 'pikachu', types: ['electric'] },
  { name: 'raichu', types: ['electric'] },
  { name: 'sandshrew', types: ['ground'] },
  { name: 'sandslash', types: ['ground'] },
  { name: 'nidoran-f', types: ['poison'] },
  { name: 'nidorina', types: ['poison'] },
  { name: 'nidoqueen', types: ['poison', 'ground'] },
  { name: 'nidoran-m', types: ['poison'] },
  { name: 'nidorino', types: ['poison'] },
  { name: 'nidoking', types: ['poison', 'ground'] },
  { name: 'clefairy', types: ['fairy'] },
  { name: 'clefable', types: ['fairy'] },
  { name: 'vulpix', types: ['fire'] },
  { name: 'ninetales', types: ['fire'] },
  { name: 'jigglypuff', types: ['normal', 'fairy'] },
  { name: 'wigglytuff', types: ['normal', 'fairy'] },
  { name: 'zubat', types: ['poison', 'flying'] },
  { name: 'golbat', types: ['poison', 'flying'] },
  { name: 'oddish', types: ['grass', 'poison'] },
  { name: 'gloom', types: ['grass', 'poison'] },
  { name: 'vileplume', types: ['grass', 'poison'] },
  { name: 'paras', types: ['bug', 'grass'] },
  { name: 'parasect', types: ['bug', 'grass'] },
  { name: 'venonat', types: ['bug', 'poison'] },
  { name: 'venomoth', types: ['bug', 'poison'] },
  { name: 'diglett', types: ['ground'] },
  { name: 'dugtrio', types: ['ground'] },
  { name: 'meowth', types: ['normal'] },
  { name: 'persian', types: ['normal'] },
  { name: 'psyduck', types: ['water'] },
  { name: 'golduck', types: ['water'] },
  { name: 'mankey', types: ['fighting'] },
  { name: 'primeape', types: ['fighting'] },
  { name: 'growlithe', types: ['fire'] },
  { name: 'arcanine', types: ['fire'] },
  { name: 'poliwag', types: ['water'] },
  { name: 'poliwhirl', types: ['water'] },
  { name: 'poliwrath', types: ['water', 'fighting'] },
  { name: 'abra', types: ['psychic'] },
  { name: 'kadabra', types: ['psychic'] },
  { name: 'alakazam', types: ['psychic'] },
  { name: 'machop', types: ['fighting'] },
  { name: 'machoke', types: ['fighting'] },
  { name: 'machamp', types: ['fighting'] },
  { name: 'bellsprout', types: ['grass', 'poison'] },
  { name: 'weepinbell', types: ['grass', 'poison'] },
  { name: 'victreebel', types: ['grass', 'poison'] },
  { name: 'tentacool', types: ['water', 'poison'] },
  { name: 'tentacruel', types: ['water', 'poison'] },
  { name: 'geodude', types: ['rock', 'ground'] },
  { name: 'graveler', types: ['rock', 'ground'] },
  { name: 'golem', types: ['rock', 'ground'] },
  { name: 'ponyta', types: ['fire'] },
  { name: 'rapidash', types: ['fire'] },
  { name: 'slowpoke', types: ['water', 'psychic'] },
  { name: 'slowbro', types: ['water', 'psychic'] },
  { name: 'magnemite', types: ['electric', 'steel'] },
  { name: 'magneton', types: ['electric', 'steel'] },
  { name: 'farfetchd', types: ['normal', 'flying'] },
  { name: 'doduo', types: ['normal', 'flying'] },
  { name: 'dodrio', types: ['normal', 'flying'] },
  { name: 'seel', types: ['water'] },
  { name: 'dewgong', types: ['water', 'ice'] },
  { name: 'grimer', types: ['poison'] },
  { name: 'muk', types: ['poison'] },
  { name: 'shellder', types: ['water'] },
  { name: 'cloyster', types: ['water', 'ice'] },
  { name: 'gastly', types: ['ghost', 'poison'] },
  { name: 'haunter', types: ['ghost', 'poison'] },
  { name: 'gengar', types: ['ghost', 'poison'] },
  { name: 'onix', types: ['rock', 'ground'] },
  { name: 'drowzee', types: ['psychic'] },
  { name: 'hypno', types: ['psychic'] },
  { name: 'krabby', types: ['water'] },
  { name: 'kingler', types: ['water'] },
  { name: 'voltorb', types: ['electric'] },
  { name: 'electrode', types: ['electric'] },
  { name: 'exeggcute', types: ['grass', 'psychic'] },
  { name: 'exeggutor', types: ['grass', 'psychic'] },
  { name: 'cubone', types: ['ground'] },
  { name: 'marowak', types: ['ground'] },
  { name: 'hitmonlee', types: ['fighting'] },
  { name: 'hitmonchan', types: ['fighting'] },
  { name: 'lickitung', types: ['normal'] },
  { name: 'koffing', types: ['poison'] },
  { name: 'weezing', types: ['poison'] },
  { name: 'rhyhorn', types: ['ground', 'rock'] },
  { name: 'rhydon', types: ['ground', 'rock'] },
  { name: 'chansey', types: ['normal'] },
  { name: 'tangela', types: ['grass'] },
  { name: 'kangaskhan', types: ['normal'] },
  { name: 'horsea', types: ['water'] },
  { name: 'seadra', types: ['water'] },
  { name: 'goldeen', types: ['water'] },
  { name: 'seaking', types: ['water'] },
  { name: 'staryu', types: ['water'] },
  { name: 'starmie', types: ['water', 'psychic'] },
  { name: 'mr-mime', types: ['psychic', 'fairy'] },
  { name: 'scyther', types: ['bug', 'flying'] },
  { name: 'jynx', types: ['ice', 'psychic'] },
  { name: 'electabuzz', types: ['electric'] },
  { name: 'magmar', types: ['fire'] },
  { name: 'pinsir', types: ['bug'] },
  { name: 'tauros', types: ['normal'] },
  { name: 'magikarp', types: ['water'] },
  { name: 'gyarados', types: ['water', 'flying'] },
  { name: 'lapras', types: ['water', 'ice'] },
  { name: 'ditto', types: ['normal'] },
  { name: 'eevee', types: ['normal'] },
  { name: 'vaporeon', types: ['water'] },
  { name: 'jolteon', types: ['electric'] },
  { name: 'flareon', types: ['fire'] },
  { name: 'porygon', types: ['normal'] },
  { name: 'omanyte', types: ['rock', 'water'] },
  { name: 'omastar', types: ['rock', 'water'] },
  { name: 'kabuto', types: ['rock', 'water'] },
  { name: 'kabutops', types: ['rock', 'water'] },
  { name: 'aerodactyl', types: ['rock', 'flying'] },
  { name: 'snorlax', types: ['normal'] },
  { name: 'articuno', types: ['ice', 'flying'] },
  { name: 'zapdos', types: ['electric', 'flying'] },
  { name: 'moltres', types: ['fire', 'flying'] },
  { name: 'dratini', types: ['dragon'] },
  { name: 'dragonair', types: ['dragon'] },
  { name: 'dragonite', types: ['dragon', 'flying'] },
  { name: 'mewtwo', types: ['psychic'] },
  { name: 'mew', types: ['psychic'] },
];

export default pokemon;

